### ISSUE TITLE
Tá an nasc le Nua-Chorpas na hÉireann briste

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#17]
Mar shampla: http://corpas.focloir.ie/nasc

**Comment by michmech** [comment]
Ní ar ár suíomh féin atá an fhadhb seo, ar ar shuíomh an chorpais. Bhí na naisc seo ag obair go dtí le déanaí ach níl níos mó.

Is suíomh de chuid Fhoras na Gaeilge (foireann an fhoclóra) é suíomh an chorpais, agus is ag Lexical Computing atá sé go fisiciúil, go bhfios dom. Fiosróidh mé an scéal leis an dá dhream.

**Comment by michmech** [comment]
Actually, tá tuairim agam go mbeidh sé deacair réiteach a fháil air seo idir na hinstitiúidí agus comhlachtaí éagsúla (seans go mbeidh comhlacht óstála focloir.ie i gceist freisin).

Tá réiteach níos simplí le fáil, is é sin, na nascanna ar téarma.ie a athrú ó seo:

```
http://corpas.focloir.ie/duine
```

go seo:

```
http://focloir.sketchengine.co.uk/auth/run.cgi/simple_search?queryselector=iqueryrow&iquery=duine
```

Mura n-éireoidh liom an réiteach "institiúideach" a fháil inniu, déanfaidh mé an t-athrú seo.

**Comment by michmech** [comment]
Mar a bhí mé ag tuar, níl an réiteach institiúideach le fáil. Mar sin, rinne mé an t-athrú sin chuig an URL "casta".

**Comment by oraghalb** [comment]
Go breá. Ar cheart https a bheith sa nasc seachas http?
