### ISSUE TITLE
Ba cheart a bheith in ann foréimsí a roghnú ar /plus/

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#21]

**Comment by michmech** [comment]
Tá cúis na faidhbe aimsithe agam. Tá TagHelper amháin, `Microsoft.AspNetCore.Mvc.TagHelpers`, ag cur isteach ar an idirghníomhacht sin a bhaineann le liosta foréimsí a chur ar fáil nuair a roghnaíonn an t-úsáideoir réimse a bhfuil foréimsí aige. Is féidir an fhadhb a réiteach ach an TagHelper a chommentáil amach sa chomhad `_ViewImports.cshtml`:

```
@using Microsoft.AspNetCore.Http.Extensions
@using StackExchange.Profiling
@addTagHelper *, WebOptimizer.Core
@addTagHelper *, MiniProfiler.AspNetCore.Mvc
@*@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers*@
```

Níl sé sin déanta agam go fóill, áfach. Tá tuairim @rodoch ag teastáil an bhfuil nó nach bhfuil sé sábháilte an TagHelper sin a fhágáil amach.

Taobhnóta: Yes, tá a fhios agam go bhfuil an roghnóir réimsí ríomhchláraithe ar bhealach beagáinín dúr. Sin is cúis le hisiú #11 freisin. Nuair a chuirfear feabhas air seo, seans go mbeidh muid ábalta an TagHelper sin ligean isteach arís.

**Comment by rodoch** [comment]
Fiosróidh mé an scéal seo (mar aon le #7)  inniu a chairde @michmech @oraghalb

**Comment by rodoch** [comment]
Tá réiteach beagán níos caolchúisí ar an cheist seo:

Fágtar `_ViewImports.cshtml` mar atá. Más gá TagHelper áirithe a dhíchumasú mar chuid de radharc faoi leith is féidir an treoir `@removeTagHelper` a chur leis an radharc féin.

Dearbhóidh mé leasuithe anois a réiteoidh na fabhtanna thuas.

**Comment by michmech** [comment]
Tá sé seo ceartaithe anois, a bhuí le @rodoch.

**Comment by oraghalb** [comment]
Tá, ach tá /plus/ (céadlódáil an lgh san áireamh) níos moille fós dá thoradh.
