### ISSUE TITLE
Ní oibríonn 'téarmaí cosúla' le haghaidh sínte fada in easnamh

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#22]
Mar shampla, [riomhaire](https://www.tearma.ie/q/riomhaire/), [fon](https://www.tearma.ie/q/fon/), [Cote d'Ivoire](https://www.tearma.ie/q/Cote%20d'Ivoire/), [creme](https://www.tearma.ie/q/creme/).

**Comment by michmech** [comment]
Tá sé seo ceartaithe anois. Bhí lúb ar lár san algartam cuardaigh a d'fhág gur fágach amach as an liosta téarmaí cosúla na téarmaí nach raibh de dhifríocht idir iad agus an téacs cuardaigh ach sínte fada (agus aicinn eile).

Ceartaíonn sé seo na cásanna seo a leanas:

- riomhaire --> ríomhaire
- fon --> fón
- Cote d'Ivoire --> Côte d'Ivoire

Ní cheartaíonn sé an cás seo:

- creme --> crème

Toisc nach bhfuil a leithéid de théarma sa bhunachar agus "crème".

**Comment by oraghalb** [comment]
Go maith. Cruthóidh mé isiú nua don fheidhmiúlacht creme --> crème brulée.
