### ISSUE TITLE
Suíomh Téarma á ransú le seoltaí ina bhfuil ionchódú na gcarachtar lochtach

### ISSUE THREAD

**Issue by rodoch** [gaois/Tearma#27]
Is ceist é seo atá ar lean ó [cheist eile](https://github.com/gaois/Gaois.QueryLogger/issues/3) a osclaíodh i stórlann Gaois.QueryLogger. Tá mionchur síos ar bhunús na faidhbe agus an fabhtcheartú a rinneadh go dtí seo ansin.

Bíonn innill chuardaigh i mbun ransaithe agus innéacsaithe ar shuíomh Téarma. Tugadh faoi deara sna logaí ar chuardaigh a choinníonn muid go mbíonn ionchódú lochtach ar charachtair a bhfuil sínte fada orthu i gcás iarratas áirithe ó innill chuardaigh áirithe (ag amharc ortsa  a Mhicrosoft Bing):

![logaí ar chuardaigh](https://user-images.githubusercontent.com/5305694/57140930-e7138a80-6db0-11e9-9df8-0352073ac167.png)

Is cosúil gurb éard a tharlaíonn ná seo:

- Déantar ransú ar leathanach amháin.
- Déantar parsáil ar na naisc ar fad ar an leathanach. Áit éigin sa phróiseas seo aistrítear ionchódú na gcarachtar sna naisc seo ó UTF-8 go [Windows-1252](https://www.i18nqa.com/debug/utf8-debug.html).
- Déantar ransú ar na naisc nuapharsáilte seo a bhfuil ionchódú lochtach orthu agus, dá bhrí sin, ní bhíonn toradh ar an iarratas.

Chruinnigh mé liosta de na carachtair lochtacha a bhíonn ann agus a gcomhionainn in UTF-8:

| UTF-8 | Windows-1252 |
| - | - |
| Á | Ã |
| á | Ã¡ |
| Ó | Ã“ |
| ó | Ã³ |
| Ú | Ãš |
| ú | Ãº |
| Í | Ã |
| í | Ã­ |
| É | Ã‰ |
| é | Ã© |

Más ea, ní fadhb dár ndéantús féin atá anseo; níl an suíomh ach ag déileáil leis na hiarratais sa riocht a dtagann siad chuige. An cheist dúinne ná ar mhaith linn 'cuidiú' leis na ransaitheoirí i gcásanna mar seo. Seo na roghanna atá ar fáil go bhfios domsa:

1. **Gan aon rud a dhéanamh** - Ar Bing agus a mhacasamhla atá an locht anseo agus níl á dhéanamh againn ach ag freastal ar na hiarratais a sheolann siad chugainn.
2. **Na hiarratais lochtacha a athscríobh** - Is féidir riail nó rialacha athscríofa a chur i bhfeidhm a d'aithneodh carachtar lochtach mar `Ã¡` agus a dhéanfadh athscríobh air mar `á` (agus, go roghnach, atreorú chuig an URL ceart). Ach tá deacracht anseo, cuid de na carachtair a aithníonn muid go bhfuil ionchódú lochtach orthu is carachtair dhlisteanacha iad i gcomhthéacsanna eile. Cuirim i gcás URL mar [`https://www.tearma.ie/q/as São Tomé agus Príncipe/ga/`](https://www.tearma.ie/q/as%20S%C3%A3o%20Tom%C3%A9%20agus%20Pr%C3%ADncipe/ga/) a bhfuil toradh cuí ag freagairt dó. Dá mbeadh athscríobh i bhfeidhm dhéanfaí `São Tomé` a athscríobh mar `Sáo Tomé`, rud nach bhfuil ceart i ndáiríre.
3. **Ionchódú URL a dhéanamh ar gach nasc ar an suíomh** - Faoi láthair léirítear formhór na nasc ar an suíomh le carachtair UTF-8 ghlana agus carachtair speisialta aistrithe ina HTML entities, ar nós `/q/as São Tomé agus Príncipe/ga/`. Dá ndéanfaí ionchódú URL orthu (trí leithéid `Uri.EscapeDataString()` a úsáid), is é sin gur `/q/asS%C3%A3o%20Tom%C3%A9%20agus%20Pr%C3%ADncipe/ga/` a bheadh ann, is dóigh nach mbacfadh nó gur chuma dá n-aistreodh Bingbot go hionchódú carachtair eile iad.

Is dócha go molfainn an tríú rogha. Is é an ceann is mó oibre sa mhéid is go mba ghá breith ar gach áit a bhfuil nasc dinimicúil ann agus an t-athrú a dhéanamh ach ní dócha go bhfuil an t-uasfás acu ann. Ní shílim go bhfuil ceachtar den dá rogha eile iomlán sásúil.

Comhairle @oraghalb @michmech?

**Comment by oraghalb** [comment]
Nílim róthógtha le Rogha 3. Mholfainn Rogha 1. @michmech?

**Comment by rodoch** [comment]
Cén fáth nach bhfuil tú tógtha leis an tríú rogha @oraghalb? (Díreach ar eagla nár mhínigh mé rud éigin go soiléir.)

**Comment by oraghalb** [comment]
Má thuigim i gceart thú, chuirfeadh Rogha 3 cuma ghránna ar na URLanna. Ní theastódh sé seo uainn. An bhfuil dul amú orm?

**Comment by rodoch** [comment]
Ní bheadh sé sin le feiceáil ag an úsáideoir. Déanann an brabhsálaí seoltaí atá ionchódaithe mar sin a thiontú ar ais i bhfoirm atá inléite ag daoine (bain triail as `https://www.tearma.ie/q/asS%C3%A3o%20Tom%C3%A9%20agus%20Pr%C3%ADncipe/ga/` a chur isteach i do bhrabhsálaí - ní fheicfidh an t-úsáideoir an méid seo fiú nuair a chliceálann siad ar an nasc ar an suíomh).

**Comment by oraghalb** [comment]
Tá go maith. Níl fadhb agam le Rogha 3 mar sin!

**Comment by oraghalb** [comment]
Actually, céard faoi má chóipeálann tú nasc sa treo eile, ón mbrabhsálaí isteach i rphost, mar shampla? Bheadh cuma ghránna air ansin, nach mbeadh? No bheadh sin sásúil dar liom.

**Comment by rodoch** [comment]
Má dhéanann tú cóipeáil trí dheaschliceáil > Cóipeáil suíomh an naisc, is ea, seo an chuma a bheadh air:

![image](https://user-images.githubusercontent.com/5305694/57587429-8f85c500-74fc-11e9-8c4e-52d17ffb4ca5.png)

Mar sin, arbh fhearr leat cloí le Rogha 1? Bhí fonn orm cúrsaí a éascú do ransaitheoirí dlisteanacha mar seo ach aontaím leat nár cheart go mbeadh taithí an úsáideora thíos leis sin.

I gcas go mbíonn tuairisciú le déanamh ar staitisticí cuardaigh, bheadh sé furast go leor na hiarratais ó Bing a eisiamh nó a mhíniú ach na torthaí a scagadh leis na seoltaí IP nó na carachair lochtacha chuí.

**Comment by rodoch** [comment]
...Ar an láimh eile, áfach, feicim go bhfuil an nós sin i bhfad níos coitianta ná mar a cheapfá. Bain triail, mar shampla, as nasc ar bith de chuid GitHub ina bhfuil carachtair speisialta a chóipeáil.

**Comment by oraghalb** [comment]
Actually, seo mar atá ar Téarma cheana, mar sin is cuma.

**Comment by rodoch** [comment]
Tá go maith. Tá rogha (3) thuas curtha i bhfeidhm ar shuíomh Téarma anois. Coinneoimis an cheist seo ar oscailt ar feadh lá nó dhó eile agus déanfaidh muid an toradh a mheas ansin.

**Comment by rodoch** [comment]
Ócé, is cosúil go bhfuil an fhadhb seo fós ann. Braithim go bhfuil minicíocht na samplaí lochtacha níos ísle ach seans ach mbaineann sé sin leis an scéal. Is léir, áfach, go mbaineann an scéal seo le Microsoft Bing i gcónaí (is féidir é sin a dheimhniú ach féachaint ar na seoltaí IP) agus ba cheart go mbeadh sé indéanta go leor na ceisteanna seo a thuairisciú dá réir sin. Molaim an cheist seo a dhruideadh muna bhfuil moltaí ag aon duine eile?
