### ISSUE TITLE
Spás gan leithead a úsáid chun timfhilleadh a éascú i dtéarmaí fada gan spás ná fleiscín.

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#34]
https://www.tearma.ie/q/methylimino/

**Comment by michmech** [comment]
Ceartaithe le commit a232c98.
Agus dála an scéil, níor bhain mé úsáid as spásanna gan leithead, bhain mé úsáid as CSS `overflow-wrap: break-word`.

**Comment by oraghalb** [comment]
Faraor níl sé ceartaithe ar scáileán cúng móibíleach.
Feicim go bhfuil gá le réiteach ar liosta na réimsí ar scáileán cúng freisin.
Tá an commit mícheart luaite agat.

**Comment by michmech** [comment]
> Faraor níl sé ceartaithe ar scáileán cúng móibíleach.

Tá. Is dócha nach raibh sé uaslódáilte go fóill nuair a bhí tú ag féachaint air. Tá anois.

> Feicim go bhfuil gá le réiteach ar liosta na réimsí ar scáileán cúng freisin.

Tá sé sin déanta freisin.

> Tá an commit mícheart luaite agat.

Mo leithscéal, seo an commit ceart: 2e2f552363aca3cfe2c2786eadb30168c6c71c64
