### ISSUE TITLE
Feabhsuithe ar an gcuardach

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#40]
- Leathnú cuardach: leama → focal (e.g. chicken wings → chicken wing).
- Leathnú cuardach: ∅ → spás/fleiscín (e.g. heatwave → heat wave, cybersecurity → cyber-security).
- Toradh gaolmhar le/gan spás/fleiscín → toradh beacht (e.g. cyber security → cyber-security).
- Leathnú cuardach: cosúlachtaí córasacha i dteanga faoi leith (e.g. -izer/-iser sa Bhéarla).

**Comment by michmech** [comment]
Déanta.

- Sa chuardach ar théarmaí gaolmhara, déantar adhá chineál leathnú anois: focal > lemma (mar a bhí cheana riamh anall) agus lemma > focal (rud nua).
  Sampla: "[chicken wings](https://www.tearma.ie/q/chicken%20wings/)" > aimseofar "chicken wing" mar thoradh gaolmhar.

- Agus torthaí beachta á gcuardach anois, déantar neamhaird ar spásanna agus fleiscíní.
  Sampla: "[heat wave](https://www.tearma.ie/q/heat%20wave/)" nó "heat-wave" nó "heatwave" > aimseofar an toradh beacht céanna.

- Agus torthaí gaolmhara á gcuradach anois, láimhseáltear an fleiscín mar a bheadh spás (agus dá bhrí sin, deighteoir focal) ann.
  Sampla: "[cyber-security](https://www.tearma.ie/q/cyber-security/)" > aimseofar torthaí gaolmhara a bhfuil na focail "cyber" agus "security" iontu.

- Sa chuardach ar thorthaí beachta, déantar leathnú anois ar phatrúin ar nós "-ize/-ise".
  Sampla: "[politicize](https://www.tearma.ie/q/politicize/)" > aimseofar "politicise" mar thoradh beacht.

- Sa chuardach ar thorthaí gaolmhara, déantar leathnú anois ar phatrúin ar nós "-ize/-ise".
  Sampla: "[capitalize](https://www.tearma.ie/q/capitalize/)" > aimseofar torthaí gaolmhara ina bhfuil formeacha de "capitalize" agus "capitalise" araon.
  
Seo iad patrúin atá i bhfeidhm faoi láthair. Is féidir tuilleadh a chur leo:

	-ize/-ise
	-izing/-ising
	-izes/-ises
	-ized/-ised

**Comment by michmech** [comment]
Tá `-iser/-izer` le cur leis an liosta patrún. Sampla: fertiliser/fertilizer.

**Comment by michmech** [comment]
Tá `-iser/-izer` curtha leis an liosta patrún.
