### ISSUE TITLE
Tá iontrálacha áirithe á dtaispeáint iliomad uaireanta i dtorthaí cuardaigh áirithe

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#5]
Cuardaigh, mar shampla: [ethernet](https://www.tearma.ie/q/ethernet/) (3583154, 3527544), [website](https://www.tearma.ie/q/website/) (4451788), [computer](https://www.tearma.ie/q/computer/) (3564421, 3576544, 3576545, 3492778, 3576773, 3576837, 3576986).

**Comment by michmech** [comment]
Ceartaithe.
