### ISSUE TITLE
Níl leathanú ag obair ar /plus/ má chuardaítear leis an tsaoróg '%'

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#6]
Féach [seo](https://www.tearma.ie/plus/%25/al/al/lang0/pos0/dom0/sub0/), mar shampla.

**Comment by oraghalb** [comment]
Baineann an fhadhb le sínte fada freisin, is cosúil. Féach [seo](https://www.tearma.ie/plus/&#xE1;bhar/al/st/langga/pos0/dom0/sub0/2/), mar shampla.

**Comment by michmech** [comment]
Ceartaithe.

**Comment by oraghalb** [comment]
Níl sé seo iomlán ceartaithe. Oibríonn leathanú le sínte fada anois. Ach ní oibríonn leathanú leis [an tsaoróg '%'](https://www.tearma.ie/plus/%25/al/al/lang0/pos0/dom0/sub0/).

**Comment by oraghalb** [comment]
Anuas air seo, ní oibríonn an cuardach casta má tá spás iomarcach ag deireadh an téacs cuardaigh, mar shampla [seo](https://www.tearma.ie/plus/iomarcach%20/al/al/lang0/pos0/dom0/sub0/) vs [seo](https://www.tearma.ie/plus/iomarcach/al/al/lang0/pos0/dom0/sub0/).

**Comment by michmech** [comment]
An rud leis an tsaoróg, tá sé ceartaithe anois.

An rud leis an spás, déarfainn nach fabht é sin ach feature. Má chuardaíonn tú `"iomarcach"` gheobhaidh tú téarmaí a bhfuil an teaghrán sin iontu (= ceithre iontráil). Má chuardaíonn tú `"iomarcach "` gheobhaidh tú, arís, tearmaí a bhfuil an teaghrán sin iontu (= náid iontráil, mar nil an teaghrán sin in aon téarma).
