### ISSUE TITLE
Glantar an fhoirm ar /plus/ nuair a chliceáiltear 'Cuardaigh/Search'

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#7]

**Comment by michmech** [comment]
Tá an chúis chéanna leis seo agus atá le hisiú #21. Is féidir an fhadhb a réiteach ach TagHelper áirithe a fhágáil amach. Tá tuairim @rodoch ag teastáil an bhfuil nó nach bhfuil sé sábháilte an TagHelper sin a fhágáil amach.

**Comment by michmech** [comment]
Tá sé seo ceartaithe anois, a bhuí le @rodoch.
