### ISSUE TITLE
Áis de dhíth chun an téacs cuardaigh a aistriú idir /q/ agus /plus/

### ISSUE THREAD

**Issue by oraghalb** [gaois/Tearma#8]

**Comment by michmech** [comment]
Déanta. As seo amach, cuimhníonn an suíomh (le cookie) cén téacs a bhí sa bhosca téacs faoi `/q/` agus/nó  faoi `/plus/` an uair dheireanach a d'athraigh an t-úsáideoir an téacs (cuma ar chliceáil an t-úsáideoir "Cuardaigh" nó nár chliceáil), agus cuireann sé an téacs ar ais isteach sa bhosca ar lódáil an leathanaigh (faoi `/q/` agus `/plus/` araon). Tá súil agam nach gcuirfidh sé seo mearbhall ar úsáideoirí!

**Comment by oraghalb** [comment]
D'fhéadfadh sé seo a bheith mearbhallach, ach fan go bhfeicfimid.

**Comment by rodoch** [comment]
An rogha eile, is dócha, ná rud éigin níos simplí, ar nós má dhéantar cuardach tapa le téarma áirithe, m.sh. "intersection" gurb éard a bhíonn sa nasc chuig an chuardach casta ag barr an scáileáin ná `https://www.tearma.ie/plus/intersection/al/al/lang0/pos0/dom0/sub0/` agus nach mbacfaí le fianán a úsáid? D'fhágfadh sé seo go ndéantar cuardach ar aistriú duit go cuardach tapa agus cuireann sé seo breis bheag leis an aga lódála. Dá gcuirfí feabhas ar #11 ar dtús báire, áfach, b'fhéidir nach scéal mór a bheadh anseo?

Ní chuireann an socrú reatha isteach orm ach amháin nuair a thagaim go leathanach baile an tsuímh as an nua agus tá téarma lódáilte isteach sa bhosca cuardaigh cheana.
